trigger:
  branches:
    include:     
      - master

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Deploy from Published Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    - script: dotnet restore ./net/DocumentService.csproj
      displayName: 'Restore dependencies'

    - script: dotnet build ./net/DocumentService.csproj --configuration Release
      displayName: 'Build application'

    - script: dotnet publish ./net/DocumentService.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container

- stage: DeployQA
  displayName: 'Deploy to QA'
  dependsOn: Build
  jobs:
  - job: CDQA
    displayName: 'Continuous Deployment to QA'
    steps:
    - download: current
      artifact: drop
      displayName: 'Download Build Artifacts'

    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  
    
    
        

    # - task: AzureRmWebAppDeployment@4
    #   displayName: 'Azure Web App Deploy to QA'
    #   inputs:
    #     ConnectionType: 'AzureRM'
    #     azureSubscription: 'Microservices_Connection'
    #     appType: 'webApp'
    #     #ResourceGroupName: 'QA-F11-Server_group'
        
    #     #WebAppName: 'webapp-msqa-cc-DocumentViewer' 
    #     WebAppName: 'webapp-ms-cc-licencedev'
    #     package: '$(Pipeline.Workspace)/drop'
       


     